##################################################################################
# Cloudify bootstrap Local Manager plugin
##################################################################################
plugins:
    bootstrap_local:
        executor: central_deployment_agent
        source: https://github.com/greggigon/bootstrap-local-manager-plugin/archive/1.2.zip
